In [5]:
import pandas as pd
import numpy as np

In [6]:
data = pd.read_csv("csd_2021.csv")

In [7]:
courses = data.iloc[:,10:]
courses

NCO-01-01  NCO-01-02  NCO-01-03  NCO-01-04  NCO-01-05  NCO-02-01  \
0        10.0       10.0       10.0        9.0       10.0        8.0   
1         6.0       10.0        7.0        8.0        7.0        8.0   
2         6.0        7.0        5.0       10.0        9.0        6.0   
3         7.0       10.0        8.0        9.0       10.0        6.0   
4        10.0       10.0       10.0       10.0       10.0       10.0   
5         7.0       10.0        6.0        7.0       10.0        7.0   
6         6.0        9.0        9.0        7.0        9.0        7.0   
7         8.0       10.0       10.0        9.0       10.0       10.0   
8         4.0        9.0        4.0        6.0       10.0        7.0   
9         7.0       10.0       10.0        8.0       10.0        9.0   
10        9.0        9.0        7.0        6.0        7.0       10.0   
11        7.0       10.0        8.0        8.0        9.0        8.0   
12        6.0       10.0        9.0        7.0        8.0        7.0   
13        1.0        5.0       -1.0       -1.0        3.0       -1.0   
14       10.0        9.0        9.0        7.0       10.0        9.0   
15        9.0        9.0        7.0        6.0        8.0        9.0   
16        8.0        8.0        7.0        5.0        9.0        8.0   
17        5.0        5.0        4.0       -1.0       -1.0        5.0   
18        6.0       10.0        8.0        5.0       -1.0        6.0   
19        5.0        8.0        5.0        7.0        6.0       -1.0   
20        6.0        8.0        7.0        6.0        2.0        8.0   
21        9.0       10.0       10.0        7.0        9.0        8.0   
22        8.0       10.0        7.0        5.0       10.0       -1.0   
23       -1.0       -1.0       -1.0       -1.0       -1.0        6.0   
24       -1.0        7.0        0.0       -1.0        4.0        3.0   
25        6.0        6.0        4.0        4.0        7.0        5.0   
26        3.0        7.0        1.0        3.0        2.0        8.0   
27        5.0        7.0        8.0        6.0        5.0        5.0   
28        4.0       10.0       10.0        8.0        7.0        6.0   
29        7.0        7.0        8.0        6.0       10.0        6.0   
30        1.0        9.0        6.0        4.0        8.0        1.0   
31        6.0        8.0        7.0        8.0       10.0        3.0   
32        7.0        9.0        4.0        5.0        8.0        7.0   
33        5.0        9.0        8.0       -1.0       -1.0        6.0   
34       10.0       10.0       10.0        9.0       10.0        9.0   
35       10.0        7.0       -1.0        9.0        7.0        8.0   
36        6.0        4.0        7.0        4.0        0.0        5.0   
37        8.0       10.0        8.0        9.0       10.0        9.0   
38        8.0        8.0        8.0        6.0        7.0        6.0   
39       10.0       10.0       10.0       10.0       10.0       10.0   
40       10.0        9.0       10.0       10.0       10.0       10.0   
41        9.0        9.0        9.0       10.0       10.0       10.0   
42        5.0        8.0        7.0        6.0       -1.0       -1.0   
43        2.0        9.0        7.0        5.0        6.0        0.0   
44       10.0        9.0        9.0        9.0       10.0        8.0   
45        7.0        6.0        7.0        6.0        5.0        8.0   
46       10.0       10.0       10.0       10.0        9.0       10.0   
47       -1.0        8.0        6.0        7.0        0.0        3.0   
48       10.0       10.0       10.0       -1.0       10.0       -1.0   
49       10.0        7.5        5.0        8.0        9.0        6.0   
50        9.0        8.0        8.0        7.0        5.0        6.0   

    NNA-06-01  NNA-06-02  NNA-07-01  NCO-02-02  ...  NGE-08-02  NGE-07-03  \
0        -1.0       -1.0       -1.0        8.0  ...       -1.0       -1.0   
1        -1.0       -1.0       -1.0        5.0  ...       -1.0       -1.0   
2        -1.0       -1.0    

In [8]:
import json
from pandas.io.json import json_normalize

with open("courses_ids_600000014.json","r") as json_file:
     json_file = json.load(json_file)
coded_courses = json_normalize(json_file['courses'])
del coded_courses['ccoursecode']
course_dict = coded_courses.set_index('coursecode')['courseId'].to_dict()

for key in course_dict.keys():
    courses.rename(columns = {key:str(course_dict[key]).strip()}, inplace=True)
display(courses)

C:\Users\sakri\Anaconda3\envs\acm\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: pandas.io.json.json_normalize is deprecated, use pandas.json_normalize instead
  


40002908  40002909  40002910  40002911  40002912  40002913  40002914  \
0       10.0      10.0      10.0       9.0      10.0       8.0      -1.0   
1        6.0      10.0       7.0       8.0       7.0       8.0      -1.0   
2        6.0       7.0       5.0      10.0       9.0       6.0      -1.0   
3        7.0      10.0       8.0       9.0      10.0       6.0      -1.0   
4       10.0      10.0      10.0      10.0      10.0      10.0      -1.0   
5        7.0      10.0       6.0       7.0      10.0       7.0      -1.0   
6        6.0       9.0       9.0       7.0       9.0       7.0      -1.0   
7        8.0      10.0      10.0       9.0      10.0      10.0      -1.0   
8        4.0       9.0       4.0       6.0      10.0       7.0      -1.0   
9        7.0      10.0      10.0       8.0      10.0       9.0      -1.0   
10       9.0       9.0       7.0       6.0       7.0      10.0      -1.0   
11       7.0      10.0       8.0       8.0       9.0       8.0      -1.0   
12       6.0      10.0       9.0       7.0       8.0       7.0      -1.0   
13       1.0       5.0      -1.0      -1.0       3.0      -1.0      -1.0   
14      10.0       9.0       9.0       7.0      10.0       9.0      -1.0   
15       9.0       9.0       7.0       6.0       8.0       9.0      -1.0   
16       8.0       8.0       7.0       5.0       9.0       8.0      -1.0   
17       5.0       5.0       4.0      -1.0      -1.0       5.0      -1.0   
18       6.0      10.0       8.0       5.0      -1.0       6.0      -1.0   
19       5.0       8.0       5.0       7.0       6.0      -1.0      -1.0   
20       6.0       8.0       7.0       6.0       2.0       8.0      -1.0   
21       9.0      10.0      10.0       7.0       9.0       8.0      -1.0   
22       8.0      10.0       7.0       5.0      10.0      -1.0      -1.0   
23      -1.0      -1.0      -1.0      -1.0      -1.0       6.0      -1.0   
24      -1.0       7.0       0.0      -1.0       4.0       3.0      -1.0   
25       6.0       6.0       4.0       4.0       7.0       5.0      -1.0   
26       3.0       7.0       1.0       3.0       2.0       8.0      -1.0   
27       5.0       7.0       8.0       6.0       5.0       5.0      -1.0   
28       4.0      10.0      10.0       8.0       7.0       6.0      -1.0   
29       7.0       7.0       8.0       6.0      10.0       6.0      -1.0   
30       1.0       9.0       6.0       4.0       8.0       1.0      -1.0   
31       6.0       8.0       7.0       8.0      10.0       3.0      -1.0   
32       7.0       9.0       4.0       5.0       8.0       7.0      -1.0   
33       5.0       9.0       8.0      -1.0      -1.0       6.0      -1.0   
34      10.0      10.0      10.0       9.0      10.0       9.0      -1.0   
35      10.0       7.0      -1.0       9.0       7.0       8.0      -1.0   
36       6.0       4.0       7.0       4.0       0.0       5.0      -1.0   
37       8.0      10.0       8.0       9.0      10.0       9.0      -1.0   
38       8.0       8.0       8.0       6.0       7.0       6.0      -1.0   
39      10.0      10.0      10.0      10.0      10.0      10.0      -1.0   
40      10.0       9.0      10.0      10.0      10.0      10.0      -1.0   
41       9.0       9.0       9.0      10.0      10.0      10.0      -1.0   
42       5.0       8.0       7.0       6.0      -1.0      -1.0      -1.0   
43       2.0       9.0       7.0       5.0       6.0       0.0      -1.0   
44      10.0       9.0       9.0       9.0      10.0       8.0      -1.0   
45       7.0       6.0       7.0       6.0       5.0       8.0      -1.0   
46      10.0      10.0      10.0      10.0       9.0      10.0      -1.0   
47      -1.0       8.0       6.0       7.0       0.0       3.0      -1.0   
48      10.0      10.0      10.0      -1.0      10.0      -1.0      -1.0   
49      10.0       7.5       5.0       8.0       9.0       6.0      -1.0   
50       9.0       8.0       8.0       7.0       5.0       6.0      -1.0   

    40002915  40002917  40002918  ...  600012836  6

In [9]:
courses_metrics = dict()
for course in courses.columns:
    
    current_course = courses[course]
    current_course = (current_course[current_course >= 0]).to_numpy()
    if len(current_course) > 0:
        courses_metrics[course] = dict()
        # print(current_course)
        average = np.average(current_course)
        print(average)
        courses_metrics[course]['average'] = float(average)
        if average < 5.0:
            difficulty =  "VERY HARD"
        elif average <= 6:
            difficulty = "HARD"
        elif average <= 8:
            difficulty =  "MEDIUM"
        else:
            difficulty = "EASY"
        print(difficulty)
        courses_metrics[course]['difficulty'] = difficulty
        print(len(current_course))
        courses_metrics[course]['enrolled'] = len(current_course)

        bins, edges = np.histogram(current_course)
        print(bins)
        courses_metrics[course]['histogram'] = bins.tolist()

7.041666666666667
MEDIUM
48
[ 2  1  1  2  5  9  7  5  5 11]
8.55
EASY
50
[ 1  2  0  2  0  7  8  0 12 18]
7.375
MEDIUM
48
[ 1  1  0  0  4  3  3 11  9 16]
7.133333333333334
MEDIUM
45
[1 3 5 0 9 8 0 6 7 6]
7.717391304347826
MEDIUM
46
[ 2  0  2  1  1  3  2  6  4 25]
6.956521739130435
MEDIUM
46
[ 1  1  0  3  0  4 10  5 10 12]
5.5
HARD
1
[0 0 0 0 0 1 0 0 0 0]
7.229166666666667
MEDIUM
48
[ 1  0  0  0  0  7  8 12  8 12]
7.7317073170731705
MEDIUM
41
[ 1  2  0  0  0  3 10 12  5  8]
7.458333333333333
MEDIUM
48
[ 2  1  4  0  2  3  6  7 12 11]
6.51063829787234
MEDIUM
47
[ 2  1  1  3  9  6 11  3  5  6]
6.264705882352941
MEDIUM
34
[ 3  1  0  1  7  6  1 11  2  2]
8.206896551724139
EASY
29
[ 3  0  4  0  3  0  3  0  6 10]
4.935483870967742
VERY HARD
31
[6 0 2 2 2 3 6 2 3 5]
6.7272727272727275
MEDIUM
33
[1 5 2 0 6 7 0 6 4 2]
8.308823529411764
EASY
34
[ 3  0  1  1  6  0  2  0 13  8]
6.655172413793103
MEDIUM
29
[1 0 2 6 0 5 6 3 3 3]
8.0
MEDIUM
38
[ 1  0  1  2  0  3  5  6 11  9]
6.651515151515151
MEDIUM
33


In [10]:
print(len(courses_metrics))

64


In [11]:
import json
with open('course_metrics.json', 'w') as fp:
    json.dump(courses_metrics, fp)